### ISSUE TITLE
How to disable message "Energy requested is outside of tabulated data, using linear extrapolation"

### ISSUE THREAD

**Issue by danielbon** [lynntf/nist-calculators#5]
I am often receiving the message "Energy requested is outside of tabulated data, using linear extrapolation". Could this be disabled?

**Comment by lynntf** [comment]
Hi Daniel,

Sorry about all the warnings. I've changed the default behavior to not warn if the attenuation coefficient at the requested energy is outside of the tabulated data. I think it could be best to just [change the default behavior of the warnings package](https://docs.python.org/3/library/warnings.html#the-warnings-filter), but this should be fine for now. To enable the warnings, add the `kwarg` `warn = True` when requesting attenuation coefficients.

Just to be clear, I don't know how valid the extrapolated data is (the extrapolated data is formed by a linear extension of the two edge values of tabulated data in the log-log space; the pair production values are extrapolated in a different space, but are zero for small energies).
